language: java
sudo: false
script: mvn clean verify
jdk:
- oraclejdk8
notifications:
  slack:
    rooms:
      - ixagency:RjIRqnnvu8FYzvydyt7cxZ2T#banorte-rentabilidad
      - ixagency:RjIRqnnvu8FYzvydyt7cxZ2T#devops_tools